postgres: &postgres
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *postgres
  database: invest
  username: invest
  password: invest

test:
  <<: *postgres
  database: invest_test
  username: invest
  password: invest
